version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    mem_limit: 2g

  node-app:
    build: .  # tells Compose: "use the Dockerfile here"
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
      - ollama
    environment:
      - ES_HOST=http://elasticsearch:9200
      - OLLAMA_API_BASE=http://ollama:11434
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - .:/usr/src/app

volumes:
  esdata:
  ollama_data: